### ISSUE TITLE
Adjust cover levels?

### ISSUE THREAD

**Issue by dajare** [standardebooks/linda-brent_incidents-in-the-life-of-a-slave-girl#1]
I don't know what the protocols and policies are around adjusting light values of cover images. It's a shame (IMO!) that so much detail is lost in this one. Here's an adjusted version (_only_ levels, not saturation, etc.) with the result as shown. Is this kind of "improvement" allowed? It would make for a "better" cover, I believe. The [current image is here][1], for quick comparison.

![cover-indidents](https://user-images.githubusercontent.com/40625/112682959-baffc780-8e68-11eb-9c39-b3a79e88f7db.jpg)

[1]: https://github.com/standardebooks/linda-brent_incidents-in-the-life-of-a-slave-girl/blob/master/images/cover.jpg

**Comment by acabal** [comment]
Sure, you can make a PR to merge that in. Thanks!
